{% set name = "du_histogram" %}
{% set version = "alpha.02" %}
{% set sha256 = "e04478643a3485934ecb0d3ce07f7b0cfe6552573a40d36e7b78254f7cae9537" %}
{% set summary = "Simple ASCII histogram of du (disk usage) output" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}.{{ version }}.tar.gz
  url: https://github.com/jmeppley/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

about:
  home: https://github.com/jmeppley/{{ name }}
  summary: {{ summary }}

build:
  number: 1

requirements:
  build:
    - python
    - numpy

  run:
    - python
    - numpy
    - docopt

test:
  commands:
      - duhist.py -h
      - duhist.py
      - duhist.py -l -t .
