{% set name = "stagecache" %}
{% set author = "jmeppley" %}
{% set version = "0.1.3" %}
{% set summary = "Module and script for staging files in local cache" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    # building from master for the alpha phase
    git_url: https://github.com/{{ author }}/{{ name }}
    git_rev: v{{ version }}

about:
  home: https://github.com/{{ author }}/{{ name }}
  summary: {{ summary }}

build:
  number: 0
  noarch: python
  script: $PYTHON -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - paramiko
    - pyyaml
    - docopt

test:
  commands:
      - stagecache -h
      - stagecache --version
