{% set version = '0.0.0.9000' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-thacklr
  version: {{ version|replace("-", "_") }}

source:

  git_url: https://github.com/jmeppley/thacklr
  git_tag: v0.0.1

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - bioconductor-ggtree
    - r-magrittr
    - r-tidyverse

  run:
    - r-base
    - bioconductor-ggtree
    - r-magrittr
    - r-tidyverse

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('thacklr')"           # [not win]
    - "\"%R%\" -e \"library('thacklr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/thackl/thacklr
  license: MIT
  summary: This R package is a collection function and snippets I routinely use. Many are very
    basic, others just haven't found a better place yet...

  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'

# The original CRAN metadata for this package was:

# Package: thacklr
# Title: A Collection of R Functions and Snippets I Often Use.
# Version: 0.0.0.9000
# Authors@R: person("Thomas", "Hackl", email = "thackl@lim4.de", role = c("aut", "cre"))
# Description: This R package is a collection function and snippets I routinely use. Many are very basic, others just haven't found a better place yet...
# Remotes: bioc::release/ggtree
# Depends: R (>= 3.4.4)
# Imports: magrittr, tidyverse, ggtree
# License: MIT
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.1.1

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
