
{% set name = "jupy_tools" %}
{% set author = "jmeppley" %}
{% set version = "0.0.4a" %}
{% set summary = "Some python tools for jupyter" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    # building from master for the alpha phase
    git_url: https://github.com/{{ author }}/{{ name }}
    git_rev: v{{ version }}

about:
  home: https://github.com/jmeppley/{{ name }}
  summary: {{ summary }}

build:
  number: 0
  noarch: python
  script: $PYTHON -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python

  run:
    - python
    - pandas
    - matplotlib
