{% set version = "7.12.1" %}

package:
  name: snakemake-minimal
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/snakemake/snakemake-{{ version }}.tar.gz
  sha256: 0401b1bd41cf1e7f14aacd1e0cd31d44926c2aab17d8b147b9136e5ba73b0e3e

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
        - snakemake = snakemake:main
        - snakemake-bash-completion = snakemake:bash_completion

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - setuptools
    - wrapt
    - requests
    - docutils
    - pyyaml
    - datrie
    - requests >=2.8.1
    - psutil
    - ratelimiter
    - configargparse
    - appdirs
    - jsonschema
    - gitpython
    - toposort
    - nbformat
    - connection_pool >=0.0.3
    - pulp >=2.0
    - smart_open >=3.0
    - filelock
    - stopit
    - tabulate
    - jinja2 >=3.0,<4.0
    - yte >=1.2,<2.0
    - retry

test:
  imports:
    - snakemake
  commands:
    - export GIT\_PYTHON_REFRESH=warn
    - snakemake --version
    - snakemake --version | grep "{{ version }}"

about:
  home: https://snakemake.github.io
  license: MIT
  summary: A popular workflow management system aiming at full in-silico reproducibility.
  description: |
        Snakemake is a workflow management system that aims to reduce the complexity
        of creating workflows by providing a fast and comfortable execution 
        environment, together with a clean and modern specification language in 
        python style. Snakemake workflows are essentially Python scripts extended 
        by declarative code to define rules. Rules describe how to create output 
        files from input files. This package provides the core snakemake functionality.
        For features like reports and remote files, check out the snakemake package 
        which provides all optional dependencies.
