{% set name = "batch_launcher" %}
{% set version = "alpha.03" %}
{% set sha256 = "ebb26e98caf11359529e11e5f0622fd5ab55f1aac008c115843c26dbc29c5685" %}
{% set summary = "Python script to fragment tasks for parallel execution " %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}.{{ version }}.tar.gz
  url: https://github.com/jmeppley/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

about:
  home: https://github.com/jmeppley/{{ name }}
  summary: {{ summary }}

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python

test:
  commands:
      - batch_launcher.py -h
