{% set name = "dynamic_remote_snake" %}
{% set author = "jmeppley" %}
{% set version = "0.0.8" %}
{% set summary = "Snakemake extension to dynamically make files remote" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    git_url: https://github.com/{{ author }}/{{ name }}
    git_rev: v{{ version }}

about:
  home: https://github.com/{{ author }}/{{ name }}
  summary: {{ summary }}

build:
  number: 1
  noarch: python
  script: $PYTHON -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3
    - pip
  run:
    - python
    - snakemake-minimal
    - pysftp
    - stagecache >=0.1

test:
    commands:
        - python -c "from jme.dynamic_remote_snake.remote import get_dl_snakefile; print(get_dl_snakefile());"
