{% set version = '0.0.0.9000' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gggenomes
  version: {{ version|replace("-", "_") }}

source:

  git_url: https://github.com/jmeppley/gggenomes
  git_tag: v0.0.0

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, rtracklayer, ggtree, patchwork, Hmisc
requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-ggplot2
    - r-jsonlite
    - r-thacklr
    - r-tidyr
    - r-gggenes
    - bioconductor-ggtree

  run:
    - r-base
    - r-ggplot2
    - r-jsonlite
    - r-thacklr
    - r-tidyr
    - r-gggenes
    - bioconductor-ggtree

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('gggenomes')"           # [not win]
    - "\"%R%\" -e \"library('gggenomes')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/thackl/gggenomes

  license: MIT
  summary: gggenomes is an extension of ggplot2 for creating complex genomic maps. It builds
    on the power of ggplot2 and tidyverse adding new ggplot-style geoms & positions
    and dplyr-style verbs to manipulate the underlying data. It implements a layout
    concept inspired by ggraph and introduces tracks to bring tidyness to the mess that
    is genomics data.

  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'

# The original CRAN metadata for this package was:

# Package: gggenomes
# Title: A Grammar of Graphics for Comparative Genomics
# Version: 0.9.4.9000
# Authors@R: c( person("Thomas", "Hackl", email = "thackl@lim4.de", role = c("aut", "cre")), person("Markus J.", "Ankenbrand", email = "iimog@iimog.org", role = c("aut")), person("Kristina", "Haslinger", email = "k.haslinger@rug.nl", role = c("ctb", "sad")))
# Description: gggenomes is an extension of ggplot2 for creating complex genomic maps. It builds on the power of ggplot2 and tidyverse adding new ggplot-style geoms & positions and dplyr-style verbs to manipulate the underlying data. It implements a layout concept inspired by ggraph and introduces tracks to bring tidyness to the mess that is genomics data.
# License: MIT
# URL: https://github.com/thackl/gggenomes
# BugReports: https://github.com/thackl/gggenomes/issues
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.1.1
# Roxygen: list(markdown = TRUE)
# Remotes: github::thackl/thacklr, bioc::release/rtracklayer
# Depends: R (>= 3.4.2), dplyr, ggplot2, gggenes, purrr, readr (>= 2.0.0), stringr, tidyr, thacklr, tibble, jsonlite, snakecase
# Suggests: testthat, rtracklayer, ggtree, patchwork, Hmisc

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
