{% set name = "py-metagenomics" %}
{% set version = "1.1.0" %}
{% set sha256 = "13f8efb4af97c51d6ce1da20fb21c1a75af0f5eef1a098f9d7c80502334d19a4" %}
{% set summary = "Some python libs and scripts for metagenomic analyses" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}.{{ version }}.tar.gz
  url: https://github.com/jmeppley/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

about:
  home: https://github.com/jmeppley/{{ name }}
  summary: {{ summary }}

build:
  number: 1
  noarch: python
  skip: True # [py26]

requirements:
  build:
    - python

  run:
    - python
    - numpy
    - biopython
    - pandas
    - simplejson
    - last
    - tantan
    - hmmer

test:
  commands:
      - screen_list.py -h
      - assign_top_hit.py -h
      - $CONDA_PREFIX/share/py-metagenomics/databases/buildRefSeqAccToTaxidMap.py -h
