{% set name = "py-metagenomics" %}
{% set version = "beta.02" %}
{% set sha256 = "21faadd6ac3ea4189351e8406d321da4336ebd6c42e47b61ec976220b04c8e04" %}
{% set summary = "Some python libs and scripts for metagenomic analyses" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}.{{ version }}.tar.gz
  url: https://github.com/jmeppley/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

about:
  home: https://github.com/jmeppley/{{ name }}
  summary: {{ summary }}

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - numpy
    - biopython
    - pandas
    - simplejson
    - last
    - tantan
    - hmmer

test:
  commands:
      - screen_list.py -h
      - assign_top_hit.py -h
      - $CONDA_PREFIX/share/py-metagenomics/databases/buildAccKOMapping.py
