{% set name = "py-metagenomics" %}
{% set version = "alpha.04" %}
{% set sha256 = "37c6014ada9b0587e1a2ec7c03b8bee836f9e9d4fb727705ce9458369d3cd413" %}
{% set summary = "Some python libs and scripts for metagenomic analyses" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}.{{ version }}.tar.gz
  url: https://github.com/jmeppley/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

about:
  home: https://github.com/jmeppley/{{ name }}
  summary: {{ summary }}

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - numpy
    - biopython
    - pandas
    - simplejson

test:
  commands:
      - screen_list.py -h
      - assign_top_hit.py -h
