{% set name = "py-metagenomics" %}
{% set version = "beta.03" %}
{% set sha256 = "232b39e627a75e126669dc4df4838236944835560c42ad4e5d72d2c4eaf2b5fd" %}
{% set summary = "Some python libs and scripts for metagenomic analyses" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}.{{ version }}.tar.gz
  url: https://github.com/jmeppley/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

about:
  home: https://github.com/jmeppley/{{ name }}
  summary: {{ summary }}

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - numpy
    - biopython
    - pandas
    - simplejson
    - last
    - tantan
    - hmmer

test:
  commands:
      - screen_list.py -h
      - assign_top_hit.py -h
      - $CONDA_PREFIX/share/py-metagenomics/databases/buildRefSeqAccToTaxidMap.py -h
