{% set name = "py-metagenomics" %}
{% set version = "1.1.1" %}
{% set sha256 = "020f8dc149a6ac2a313a5ca11a76e7762e90d6aa02879f25de0544b731b51657" %}
{% set summary = "Some python libs and scripts for metagenomic analyses" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}.{{ version }}.tar.gz
  url: https://github.com/jmeppley/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

about:
  home: https://github.com/jmeppley/{{ name }}
  summary: {{ summary }}

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - numpy
    - biopython
    - pandas
    - simplejson
    - last
    - tantan
    - hmmer

test:
  commands:
      - screen_list.py -h
      - assign_top_hit.py -h
      - $CONDA_PREFIX/share/py-metagenomics/databases/buildRefSeqAccToTaxidMap.py -h
