{% set name = "py-metagenomics" %}
{% set version = "beta.01" %}
{% set sha256 = "8180e9717c1656a65464a45686bfc842b133697f711d48889c28939cab233668" %}
{% set summary = "Some python libs and scripts for metagenomic analyses" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}.{{ version }}.tar.gz
  url: https://github.com/jmeppley/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

about:
  home: https://github.com/jmeppley/{{ name }}
  summary: {{ summary }}

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - numpy
    - biopython
    - pandas
    - simplejson

test:
  commands:
      - screen_list.py -h
      - assign_top_hit.py -h
