
{% set name = "proovframe" %}
{% set author = "thackl" %}
{% set version = "0.9.7" %}
{% set summary = "frame-shift correction for long read (meta)genomics" %}
{% set sha256 = "5e33556fd682095712a25ee00aabbd5c9935c39cf7339e39a9aeb4d00d5991ca" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    # building from master for the alpha phase
    git_url: https://github.com/{{ author }}/{{ name }}
    git_rev: v{{ version }}

about:
  home: https://github.com/{{ author }}/{{ name }}
  summary: {{ summary }}

build:
  number: 1

requirements:
  build:
    - perl
  run:
    - perl
    - perl-data-dumper
    - diamond >=2.0.3

test:
  commands:
      - proovframe -h
      - proovframe map -h
      - proovframe-fix -h
