{% set name = "FinishM" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 3
  script:
      - "gem install finishm -v {{ version }}"
      - "sh $RECIPE_DIR/munge_shebangs.sh"

requirements:
  host:
    - ruby >=2.4, <2.6
    - gxx_linux-64
  run:
    - ruby >=2.4, <2.6
    - graphviz
    - velvet
    - clustalo

about:
    home: 'https://github.com/wwood/finishm'
    license: "MIT License"
    summary: "FinishM attempts to improve draft genomes by considering the computational problem to be about finishing, not assembly in the traditional sense."

