
{% set name = "seq-scripts" %}
{% set author = "thackl" %}
{% set version = "0.0.1" %}
{% set summary = "assorted bio sequence tools from thackl" %}

package:
  name: {{ author }}-{{ name|lower }}
  version: {{ version }}

source:
    # building from master for the alpha phase
    # git_url: https://github.com/{{ author }}/{{ name }}
    git_url: https://github.com/jmeppley/{{ name }}
    git_rev: v{{ version }}

about:
  home: https://github.com/{{ author }}/{{ name }}
  summary: {{ summary }}

build:
  number: 0

requirements:
  build:
    - perl
  run:
    - perl
    - perl-math-random
    - perl-data-dumper

test:
  commands:
      - seq-len -h
